site_name: Phaistos
theme:
  name: simple-blog
  highlightjs: true
  hljs_languages:
    - yaml
    - python
  favicon: assets/images/favicon.ico
plugins:
  - mkdocstrings
nav:
  - Phaistos: index.md
