name: Build and publish Phaistos
run-name: Publish Phaistos distributions to PyPI and TestPyPI 🐍
on:
  push:
    tags:
      - "v*"
concurrency:
  group: ${{ github.ref }}-publish
  cancel-in-progress: true

jobs:
  build-and-publish:
    name: Build Phaistos package 📦
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.event.ref }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install pypa/build
      run: |
        python3
          -m
            pip
              install
              build
              --user
    - name: Build a binary wheel and a source tarball
      run: |
        python3
          -m
            build
              --sdist
              --wheel
              --outdir
                dist/
        .
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
